sonar.projectKey=movimientos_contables_mid
sonar.projectName=movimientos_contables_mid
sonar.projectVersion=0.2.1

sonar.sources=.
sonar.exclusions=swagger/**,routers/commentsRouter_controllers.go,**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.sourceEncoding=UTF-8
