swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /transaccion_movimientos/:
    post:
      tags:
      - transaccion_movimientos
      description: create PostTransaccionMovimientos
      operationId: TransaccionMovimientosController.PostTransaccionMovimientos
      parameters:
      - in: body
        name: body
        description: body for TransaccionMovimientos content
        required: true
        schema:
          $ref: '#/definitions/models.TransaccionMovimientos'
      responses:
        "201":
          description: Ok
        "400":
          description: the request contains incorrect syntax
        "500":
          description: Unhandled Error
  /transaccion_movimientos/{idType}/{id}:
    get:
      tags:
      - transaccion_movimientos
      description: Get TransaccionMovimientos
      operationId: TransaccionMovimientosController.Get TransaccionMovimientos
      parameters:
      - in: path
        name: idType
        description: 'buscar por id de: consecutivo o transaccion'
        required: true
        type: string
      - in: path
        name: id
        description: El ID como tal
        required: true
        type: integer
        format: int64
      - in: query
        name: detailed
        description: Traer los movimientos asociados? `false` por defecto
        type: boolean
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TransaccionMovimientos'
        "400":
          description: Parametros Incorrectos
        "404":
          description: Transaccion no encontrada
        "500":
          description: Error no manejado!
        "502":
          description: Error al contactar otra API
  /transaccion_movimientos/transaccion_movimientos:
    post:
      tags:
      - transaccion_movimientos
      description: 'create PostTransaccionMovimientos - DEPRECADA: Se eliminará a
        futuro. Por favor usar el endpoint sencillo, sin el `transaccion_movimientos`
        adicional'
      operationId: TransaccionMovimientosController.PostTransaccionMovimientosDeprecada
      parameters:
      - in: body
        name: body
        description: body for TransaccionMovimientos content
        required: true
        schema:
          $ref: '#/definitions/models.TransaccionMovimientos'
      responses:
        "201":
          description: Ok
        "400":
          description: the request contains incorrect syntax
        "500":
          description: Unhandled Error
definitions:
  2163.0xc0005226f0.false:
    title: "false"
    type: object
  models.MovimientoResumido:
    title: MovimientoResumido
    type: object
    properties:
      Activo:
        type: boolean
      CuentaId:
        type: string
      Descripcion:
        type: string
      NombreCuenta:
        type: string
      TerceroId:
        type: integer
        format: int64
      TipoMovimientoId:
        type: integer
        format: int64
      Valor:
        type: number
        format: double
  models.TransaccionMovimientos:
    title: TransaccionMovimientos
    type: object
    properties:
      Activo:
        type: boolean
      Comprobante:
        $ref: '#/definitions/2163.0xc0005226f0.false'
      ConsecutivoId:
        type: integer
        format: int64
      Descripcion:
        type: string
      Etiquetas:
        type: string
      FechaTransaccion:
        type: string
        format: datetime
      movimientos:
        type: array
        items:
          $ref: '#/definitions/models.MovimientoResumido'
tags:
- name: transaccion_movimientos
  description: |
    TransaccionMovimientosController operations for TransaccionMovimientos
