swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /transaccion_movimientos/transaccion_movimientos:
    post:
      tags:
      - transaccion_movimientos
      description: create PostTransaccionMovimientos
      operationId: TransaccionMovimientosController.PostTransaccionMovimientos
      parameters:
      - in: body
        name: body
        description: body for TransaccionMovimientos content
        required: true
        schema:
          $ref: '#/definitions/models.TransaccionMovimientos'
      responses:
        "201":
          description: Ok
        "400":
          description: the request contains incorrect syntax
definitions:
  1731.0xc0003efd70.false:
    title: "false"
    type: object
  models.TransaccionMovimientos:
    title: TransaccionMovimientos
    type: object
    properties:
      Activo:
        type: boolean
      ConsecutivoId:
        type: integer
        format: int64
      Descripcion:
        type: string
      Etiquetas:
        type: string
      FechaTransaccion:
        type: string
        format: datetime
      movimientos:
        type: array
        items:
          $ref: '#/definitions/1731.0xc0003efd70.false'
tags:
- name: transaccion_movimientos
  description: |
    TransaccionMovimientosController operations for TransaccionMovimientos
